name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Lint (ruff/black)
        working-directory: backend
        run: |
          ruff check .
          black --check .
      - name: Type check (mypy)
        working-directory: backend
        run: mypy app/
      - name: Tests (pytest)
        working-directory: backend
        run: pytest -q

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - name: Install deps
        working-directory: frontend
        run: |
          npm ci || npm i
      - name: Lint
        working-directory: frontend
        run: npm run lint
      - name: Type check
        working-directory: frontend
        run: npx tsc --noEmit
      - name: Tests
        working-directory: frontend
        run: npm test --silent
